language: 'python'
python:
  - '3.7'
script:
  - 'true'
deploy:
  provider: 'pypi'
  user: 'hubpav'
  password:
    secure: 'ZaPVevgj0XHRGD8AjpbXsYBBgu5F4sJwrUgu6LTVj2psTxCIuZ97ghteqtxbpR5JbhaYOTot/8KHIWJTS6cRpK4oN161tOT4g3uYLD8VZB0mhTyYRjL2nsTF1ZRwB3eefcLZc6r18BCWnsHwTDxka6TSrDXhzBTg8nqI14SPyZt4OEvd2RxYrZ1nwQYJfEoiM8ZeY2zGc6mkTbxJ9xJepP5NTthUKBPw1oQex9B/ceNiicTDUkV3tgoCMMz4e3OHc6NqZ5PoOg3kXxTYRk/U38RV0LYKO0nz/O2fyFUjcJAznpTS8UJ6K/Ou2eQ6x4Xos7O9lpPPdYXHAO9ejmBBT29Nv0aiZugc0L1fmx8HOo+O9B/10+bglpHPrGy8J3wNI11qmLzScK7Rso806uReYKwbkh5ihti8E7pkHh7278NXjG36DtIpmXQ5U/vjHq/xomjlSV+wC+aoqpa2Nl6gtXef2DapLKSRHQlDeSVorAvBREVtxSEsszdu6GyDEWrsWDwcXLxyzen4zEBDGTQ04NIlvTQr9s5tOgIEN5R1MCH67ZXDRDpql2g+TaGNCvhIJMpoexjnp7PDUdx/7Jb9DNh+nTFxP0iIxuX8KCmdS4L2XM15qxgPQ83yIxJ1QCiiRINFLCFOZDahE7AdyQMUS+XAA1UxohFaRxhWGvZIywk='
  distributions: 'sdist bdist_wheel'
  on:
    tags: true
