TITLE = 'te'
VERSION = '1.0.1'
DESCRIPTION = 'Toggl Entry - CLI REST API client for Toggl'
AUTHOR = 'Pavel Hübner'
EMAIL = 'pavel.hubner@gmail.com'
URL = 'https://github.com/hubpav/te'
LICENSE = 'MIT'
